language: android
sudo: false
android:
  components:
    - build-tools-23.0.1
    - android-23
script:
- "./gradlew build test"
deploy:
  provider: script
  script: "./release.sh"
  on:
    tags: true
    repo: DeployGate/deploygate-android-sdk
after_deploy:
- 'curl -X POST --data-urlencode "payload={\"text\": \"Released a deploygate-android-sdk in Maven Central! Please check <https://oss.sonatype.org/content/groups/public/com/deploygate/|public>
  or <https://oss.sonatype.org/index.html#stagingRepositories|stagingRepositories>\"}" $SLACK_URL'
