language: android
sudo: false
android:
  components:
    - build-tools-27.0.3
    - android-27
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $ANDROID_HOME/build-tools/27.0.3
    - $ANDROID_HOME/platforms/android-27
    - $ANDROID_HOME/extras/android/m2repository
    - $ANDROID_HOME/extras/google/m2repository
before_install:
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo $ANDROID_SDK_LICENSE > $ANDROID_HOME/licenses/android-sdk-license
  - echo $ANDROID_SDK_PREVIEW_LICENSE > $ANDROID_HOME/licenses/android-sdk-preview-license
script:
  - "./gradlew build test"
deploy:
  provider: script
  script: "./release.sh"
  on:
    tags: true
    repo: DeployGate/deploygate-android-sdk
after_deploy:
  - 'curl -X POST --data-urlencode "payload={\"text\": \"Just released new deploygate-android-sdk on <https://bintray.com/deploygate/maven/com.deploygate%3Asdk|Bintray>!\"}" $SLACK_URL'
