version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2022.03
    working_directory: ~/deploygate-android-sdk
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'

commands:
  restore_gradle_cache:
    parameters: &gradle_cache_parameters
      cache_version:
        type: string
        default: v1
    steps:
      - run: .circleci/generate_checksum > gradle.checksum
      - restore_cache:
          keys:
            - gradle-<< parameters.cache_version >>-{{ checksum "gradle.checksum" }}
  save_gradle_cache:
    parameters: *gradle_cache_parameters
    steps:
      - save_cache:
          paths:
            - ~/.android
            - ~/.gradle
            - .gradle
            - ~/.m2
          key: gradle-<< parameters.cache_version >>-{{ checksum "gradle.checksum" }}

jobs:
  build:
    executor: android
    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew sdk:build sdkMock:build --continue
      - save_gradle_cache
  test:
    executor: android
    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew sdk:test sdkMock:test --continue
      - save_gradle_cache
      - store_test_results:
          path: sdk/build/test-results
          when: always
      - store_test_results:
          path: sdkMock/build/test-results
          when: always

workflows:
  version: 2
  on_commit:
    jobs:
      - build
      - test
