name: Release artifacts

on:
  pull-request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.x'
          java-package: jdk
          cache: 'gradle'
      - run: ./gradlew sample:assembleRelease
      - if: >
          secrets.SHARED_DEPLOYGATE_APP_OWNER_NAME_FOR_PUBLIC_REPO
        name: upload mock sdk apk
        run: >
          curl
          -F file=@./sample/build/outputs/bundle/mockSdkRelease/sample-mockSdk-release.aab
          -F distribution_name="sdk/pulls/${{ github.event.pull_request.number }}"
          -H 'Authorization: token ${{ secrets.SHARED_DEPLOYGATE_API_TOKEN_FOR_PUBLIC_REPO }}'
          --url 'https://deploygate.com/api/users/${{ secrets.SHARED_DEPLOYGATE_APP_OWNER_NAME_FOR_PUBLIC_REPO }}/apps'
      - if: >
          secrets.SHARED_DEPLOYGATE_APP_OWNER_NAME_FOR_PUBLIC_REPO
        name: upload real sdk apk
        run: >
          curl
          -F file=@./sample/build/outputs/bundle/realSdkRelease/sample-realSdk-release.aab
          -F distribution_name="sdk/pulls/${{ github.event.pull_request.number }}"
          -H 'Authorization: token ${{ secrets.SHARED_DEPLOYGATE_API_TOKEN_FOR_PUBLIC_REPO }}'
          --url 'https://deploygate.com/api/users/${{ secrets.SHARED_DEPLOYGATE_APP_OWNER_NAME_FOR_PUBLIC_REPO }}/apps'
